# Generated by Django 2.0.7 on 2018-08-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='c_times',
            field=models.IntegerField(blank=True, null=True, verbose_name='限制次数'),
        ),
    ]
