# Generated by Django 2.0.7 on 2018-08-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebate', '0002_auto_20180803_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='apply_time',
            field=models.DateTimeField(verbose_name='申请时间/信息'),
        ),
        migrations.RemoveField(
            model_name='site',
            name='game',
        ),
        migrations.AddField(
            model_name='site',
            name='game',
            field=models.ManyToManyField(to='rebate.Items', verbose_name='所管游戏'),
        ),
    ]
