# Generated by Django 2.0.7 on 2018-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebate', '0003_auto_20180803_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='rec',
            name='lock',
            field=models.BooleanField(default=False, verbose_name='锁定'),
        ),
    ]
